# .netlify.toml

[build]
  command = "npm install && npm run build"  # Adjust the build command as needed
  publish = "server/dist"                   # Specify the directory containing the server build output
  functions = "server/functions"            # Optional: Specify the directory containing serverless functions if applicable

[context.production]
  command = "npm install && npm run build"  # Adjust for production environment if needed
  publish = "server/dist"

[context.branch-deploy]
  command = "npm install && npm run build"  # Adjust for branch deploys if needed
  publish = "server/dist"
